function defaults = hexapod_zmp_defaults()
%HEXAPOD_ZMP_DEFAULTS Default parameters for ZMP light-control bootstrap.

defaults = struct( ...
    'F_enter', 45.0, ...
    'F_exit', 30.0, ...
    'SM_safe', 0.15, ...
    'SM_critical', 0.05, ...
    'K_yaw_zmp', 0.40, ...
    'K_x_guard', 0.20, ...
    'yaw_assist_limit_deg', 12.0, ...
    'x_guard_limit_m', 0.030, ...
    'yaw_filter_alpha', 0.35, ...
    'x_guard_filter_alpha', 0.30, ...
    'freeze_force_threshold_n', 80.0, ...
    'freeze_hold_steps', 8 ...
    );
end
