function cases = hexapod_compare_cases()
root_external = 'D:\codehub\hexapod\轨迹仿真程序';
root_current = fileparts(fileparts(fileparts(mfilename('fullpath'))));

cases = struct( ...
    'case_id', { ...
        'slope_current', 'slope_baseline', 'step_current', 'step_initial', ...
        'ditch_initial', 'ditch_half_mid', 'ditch_final_replay', 'ditch_final_closed_loop'}, ...
    'scene_name', { ...
        'slope', 'slope', 'step', 'step', ...
        'ditch', 'ditch', 'ditch', 'ditch'}, ...
    'scene_variant', { ...
        'current', 'baseline', 'current', 'initial', ...
        'initial', 'half_mid', 'final_replay', 'final_closed_loop'}, ...
    'description', { ...
        '当前斜坡方案', '斜坡旧版轨迹', '当前高台方案', '高台最初版（拆分自 origin 基线）', ...
        '深沟最初版（拆分自 origin 基线）', '深沟中间版（half）', '深沟最终版回放', '深沟最终版闭环'}, ...
    'source_type', { ...
        'pg_current', 'mat_file', 'pg_current', 'origin_step_initial', ...
        'origin_ditch_initial', 'ditch_half_replay', 'mat_file', 'ditch_final_closed_loop'}, ...
    'pattern', { ...
        'slope', 'slope', 'climb2wall', 'climb2wall', ...
        'ditch', 'ditch', 'ditch', 'ditch'}, ...
    'mat_path', { ...
        '', fullfile(root_external, 'MAIN', '6leg_motion', 'export_data', 'walk_slope_backup.mat'), '', '', ...
        '', fullfile(root_external, 'MAIN', '6leg_motion', 'ditch', 'success', 'export_data', 'walk_ditch_learned.mat'), fullfile(root_current, 'MAIN', '6leg_motion', 'ditch', 'export_data', 'walk_ditch_learned.mat'), ''}, ...
    'script_path', { ...
        '', '', '', fullfile(root_external, 'MAIN', '6leg_motion', 'export_data', 'origin', 'walk3step.m'), ...
        fullfile(root_external, 'MAIN', '6leg_motion', 'export_data', 'origin', 'walk3step.m'), fullfile(root_external, 'MAIN', '6leg_motion', 'ditch', 'success', 'CoppeliaSim_learn_ditch_half.m'), '', fullfile(root_current, 'MAIN', '6leg_motion', 'ditch', 'CoppeliaSim_learn_ditch.m')});
end
